spring.application.name=mealz
server.port=8080
logging.level.root=INFO
spring.application.version=0.1.0
spring.datasource.url=jdbc:postgresql://db.jedjvqjybublaqzetvaz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=#%Pv4wA7xX$z_rC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# JWT Settings
# Generate a strong secret key for production. This is just an example.
app.jwtSecret=your-super-strong-secret-key-that-is-at-least-256-bits-long-for-hs512
# Access Token validity in milliseconds (5 minutes)
app.jwtExpirationInMs=300000
# Refresh Token validity in milliseconds (7 days)
app.jwtRefreshExpirationInMs=604800000